version: '3.8'

services:
  db:
    image: postgres:15
    container_name: studypals_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: studypals
      POSTGRES_USER: postgres_db
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"
    volumes:
      - postgres_data_2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_db -d studypals"]
      interval: 5s
      timeout: 5s
      retries: 5
#    jpa:
#      hibernate:
#        ddl-auto: update

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studypals_app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/studypals
      SPRING_DATASOURCE_USERNAME: postgres_db
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"


volumes:
  postgres_data_2: