#!/bin/sh

MSG_FILE="$1"
MSG="$(cat "$MSG_FILE")"

# Format: type(module): description
# type: fix|feat|refactor|perf|docs|test|chore|build|ci
# module: backend|frontend|db|infra|deps|config|core|multi
REGEX='^(fix|feat|refactor|perf|docs|test|chore|build|ci)\((backend|frontend|db|infra|deps|config|core|multi)\): .+$'

if echo "$MSG" | grep -Eq "$REGEX"; then
  exit 0
fi

echo "Invalid commit message format." 1>&2
echo "Expected: type(module): description" 1>&2
echo "Example: feat(frontend): добавил страницу входа в систему" 1>&2
exit 1
