-- ================= Users =================
CREATE TABLE users (
    id bigint generated by default as identity,
    login varchar(40) not null unique,
    email varchar(50) not null unique,
    password varchar(255) not null,
    name varchar(30),
    surname varchar(30),
    description TEXT,
    profile_picture varchar(255),
    created_at timestamp(6) with time zone,
    primary key (id)
);

-- ================= Courses =================
CREATE TABLE courses (
    id bigint generated by default as identity,
    owner_id bigint not null,
    title varchar(200) not null,
    description TEXT,
    visibility varchar(255) not null check (visibility in ('PUBLIC','FRIENDS_ONLY','CERTAIN_PEOPLE')),
    moderation_status varchar(255) check (moderation_status in ('PENDING','APPROVED','REJECTED')),
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    primary key (id)
);

-- ================= Steps =================
CREATE TABLE steps (
    id bigint generated by default as identity,
    course_id bigint not null,
    name varchar(255) not null,
    description TEXT,
    content TEXT,
    type varchar(255) check (type in ('THEORY','TEST','PRACTICE')),
    primary key (id)
);

-- ================= Step Edges =================
CREATE TABLE step_edges (
    id bigint generated by default as identity,
    course_id bigint not null,
    from_step_id bigint not null,
    to_step_id bigint not null,
    required_score integer,
    primary key (id),
    unique (from_step_id, to_step_id)
);

-- ================= Course Enrollments =================
CREATE TABLE course_enrollments (
    id bigint generated by default as identity,
    course_id bigint not null,
    user_id bigint not null,
    enrolled_at timestamp(6) with time zone not null,
    primary key (id),
    unique (course_id, user_id)
);

-- ================= Course Memberships =================
CREATE TABLE course_memberships (
    id bigint generated by default as identity,
    course_id bigint not null,
    user_id bigint not null,
    granted_by bigint,
    ability varchar(255) not null check (ability in ('READ','EDIT','ADMIN')),
    primary key (id),
    unique (course_id, user_id)
);

-- ================= Friend Requests =================
CREATE TABLE friend_requests (
    requester_id bigint not null,
    user_id bigint not null,
    primary key (requester_id, user_id),
    constraint chk_no_self_request check (requester_id != user_id)
);

-- ================= User Friends =================
CREATE TABLE user_friends (
    friend_id bigint not null,
    user_id bigint not null,
    primary key (friend_id, user_id),
    constraint chk_no_self_friend check (user_id != friend_id)
);

-- ================= User Bans =================
CREATE TABLE user_bans (
    banned_user_id bigint not null,
    user_id bigint not null,
    primary key (banned_user_id, user_id),
    constraint chk_no_self_ban check (user_id != banned_user_id)
);

-- ================= User Contacts =================
CREATE TABLE user_contacts (
    user_id bigint not null,
    contact varchar(255)
);

-- ================= Foreign Keys =================
alter table courses add constraint fk_courses_owner foreign key (owner_id) references users on delete cascade;

alter table steps add constraint fk_steps_course foreign key (course_id) references courses on delete cascade;

alter table step_edges add constraint fk_step_edges_course foreign key (course_id) references courses on delete cascade;
alter table step_edges add constraint fk_step_edges_from foreign key (from_step_id) references steps on delete cascade;
alter table step_edges add constraint fk_step_edges_to foreign key (to_step_id) references steps on delete cascade;

alter table course_enrollments add constraint fk_enrollments_course foreign key (course_id) references courses on delete cascade;
alter table course_enrollments add constraint fk_enrollments_user foreign key (user_id) references users on delete cascade;

alter table course_memberships add constraint fk_memberships_course foreign key (course_id) references courses on delete cascade;
alter table course_memberships add constraint fk_memberships_user foreign key (user_id) references users on delete cascade;
alter table course_memberships add constraint fk_memberships_granted_by foreign key (granted_by) references users on delete set null;

alter table friend_requests add constraint fk_requests_user foreign key (user_id) references users on delete cascade;
alter table friend_requests add constraint fk_requests_requester foreign key (requester_id) references users on delete cascade;

alter table user_friends add constraint fk_friends_user foreign key (user_id) references users on delete cascade;
alter table user_friends add constraint fk_friends_friend foreign key (friend_id) references users on delete cascade;

alter table user_bans add constraint fk_bans_user foreign key (user_id) references users on delete cascade;
alter table user_bans add constraint fk_bans_banned foreign key (banned_user_id) references users on delete cascade;

alter table user_contacts add constraint fk_contacts_user foreign key (user_id) references users on delete cascade;

-- ================= Indexes =================
CREATE INDEX idx_courses_owner ON courses(owner_id);
CREATE INDEX idx_courses_visibility ON courses(visibility);

CREATE INDEX idx_steps_course ON steps(course_id);

CREATE INDEX idx_step_edges_course ON step_edges(course_id);
CREATE INDEX idx_step_edges_from ON step_edges(from_step_id);
CREATE INDEX idx_step_edges_to ON step_edges(to_step_id);

CREATE INDEX idx_enrollments_user ON course_enrollments(user_id);
CREATE INDEX idx_enrollments_course ON course_enrollments(course_id);

CREATE INDEX idx_memberships_user ON course_memberships(user_id);