CREATE TABLE course_chat_messages (
    id bigint generated by default as identity,
    course_id bigint not null,
    sender_id bigint not null,
    content TEXT not null,
    created_at timestamp(6) with time zone not null,
    primary key (id)
);

alter table course_chat_messages add constraint fk_course_chat_messages_course foreign key (course_id) references courses on delete cascade;
alter table course_chat_messages add constraint fk_course_chat_messages_sender foreign key (sender_id) references users on delete cascade;

CREATE INDEX idx_course_chat_messages_course_created ON course_chat_messages(course_id, created_at DESC);