CREATE TABLE course_reviews (
    id bigint generated by default as identity,
    course_id bigint not null,
    user_id bigint not null,
    rating integer not null,
    text varchar(5000),
    timestamp timestamp(6) with time zone not null,
    is_updated boolean not null default false,
    primary key (id),
    unique (course_id, user_id)
);

alter table course_reviews
    add constraint fk_course_reviews_course
    foreign key (course_id) references courses(id) on delete cascade;

alter table course_reviews
    add constraint fk_course_reviews_user
    foreign key (user_id) references users(id) on delete cascade;

CREATE INDEX idx_course_reviews_course_timestamp ON course_reviews(course_id, timestamp DESC);