spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studypals
    username: postgres
    password: postgres

logging:
  level:
    root: INFO
    com.course: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

user:
  maxFriends: 500
  maxBanUsers: 500
  enableProfilePicture: false
  minLenUser: 5
  minLenPassword: 5
  enablePasswordDigitsValidation: true