CREATE TYPE "visibility_enum" AS ENUM (
  'PUBLIC',
  'FRIENDS_ONLY',
  'CERTAIN_PEOPLE'
);

CREATE TYPE "moderation_status_enum" AS ENUM (
  'PENDING',
  'APPROVED',
  'REJECTED'
);

CREATE TYPE "ability_enum" AS ENUM (
  'READ',
  'EDIT',
  'ADMIN'
);

CREATE TYPE "step_type_enum" AS ENUM (
  'THEORY',
  'TEST',
  'PRACTICE'
);

CREATE TYPE "question_type_enum" AS ENUM (
  'TEXT_INPUT',
  'SINGLE_CHOICE',
  'MULTIPLE_CHOICE'
);

CREATE TYPE "contact_type_enum" AS ENUM (
  'PHONE',
  'TELEGRAM',
  'EMAIL',
  'OTHER'
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "login" varchar(40) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "email" varchar(50) UNIQUE NOT NULL,
  "profile_picture" varchar(255) DEFAULT '',
  "name" varchar(30) DEFAULT '',
  "surname" varchar(30) DEFAULT '',
  "description" text DEFAULT '',
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "user_contacts" (
  "user_id" bigint NOT NULL,
  "contact_type" contact_type_enum NOT NULL,
  "contact" varchar(255) NOT NULL
);

CREATE TABLE "user_friends" (
  "user_id" bigint NOT NULL,
  "friend_id" bigint NOT NULL,
  PRIMARY KEY ("user_id", "friend_id")
);

CREATE TABLE "user_bans" (
  "user_id" bigint NOT NULL,
  "banned_user_id" bigint NOT NULL,
  PRIMARY KEY ("user_id", "banned_user_id")
);

CREATE TABLE "friend_requests" (
  "user_id" bigint NOT NULL,
  "requester_id" bigint NOT NULL,
  PRIMARY KEY ("user_id", "requester_id")
);

CREATE TABLE "courses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(200) NOT NULL,
  "description" text,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "owner_id" bigint NOT NULL,
  "visibility" visibility_enum NOT NULL DEFAULT 'FRIENDS_ONLY',
  "moderation_status" moderation_status_enum,
  "comments_enabled" boolean NOT NULL DEFAULT true
);

CREATE TABLE "course_enrollments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "enrolled_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "course_memberships" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "ability" ability_enum NOT NULL DEFAULT 'READ',
  "granted_by" bigint
);

CREATE TABLE "steps" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "content" text,
  "course_id" bigint NOT NULL,
  "type" step_type_enum NOT NULL DEFAULT 'THEORY'
);

CREATE TABLE "step_edges" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "from_step_id" bigint NOT NULL,
  "to_step_id" bigint NOT NULL,
  "required_score" int,
  "course_id" bigint NOT NULL
);

CREATE TABLE "private_chat_rooms" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" bigint,
  "step_id" bigint,
  "name" varchar(200) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "private_chat_participants" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chat_room_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "joined_at" timestamp NOT NULL DEFAULT (now()),
  "last_read_message_id" bigint
);

CREATE TABLE "private_chat_messages" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chat_room_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "content" text NOT NULL,
  "sent_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp,
  "reply_to_message_id" bigint
);

CREATE TABLE "comments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "author_id" bigint NOT NULL,
  "course_id" bigint,
  "step_id" bigint,
  "content" text NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "parent_comment_id" bigint
);

CREATE TABLE "boards" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "step_id" bigint UNIQUE NOT NULL,
  "data" json NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "version" int NOT NULL DEFAULT 0
);

CREATE TABLE "tests" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "step_id" bigint UNIQUE NOT NULL,
  "time_limit_minutes" int,
  "attempts_allowed" int DEFAULT 1,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "questions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "test_id" bigint NOT NULL,
  "text" text NOT NULL,
  "type" question_type_enum NOT NULL,
  "points" int NOT NULL DEFAULT 1,
  "order_index" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "correct_text" text
);

CREATE TABLE "choice_questions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "question_id" bigint NOT NULL,
  "order_number" int NOT NULL,
  "text" text,
  "is_correct" boolean
);

CREATE TABLE "test_attempts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "test_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "attempt_number" int NOT NULL,
  "started_at" timestamp NOT NULL DEFAULT (now()),
  "completed_at" timestamp,
  "score" int
);

CREATE TABLE "user_answers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "test_attempt_id" bigint NOT NULL,
  "question_id" bigint NOT NULL,
  "type" question_type_enum NOT NULL,
  "text" text,
  "is_correct" boolean
);

CREATE TABLE "choice_user_answers" (
  "user_answer_id" bigint NOT NULL,
  "choice_question_id" bigint NOT NULL,
  PRIMARY KEY ("user_answer_id", "choice_question_id")
);

CREATE UNIQUE INDEX ON "user_contacts" ("user_id", "contact");

CREATE UNIQUE INDEX ON "course_enrollments" ("course_id", "user_id");

CREATE UNIQUE INDEX ON "course_memberships" ("course_id", "user_id");

CREATE UNIQUE INDEX ON "step_edges" ("from_step_id", "to_step_id");

CREATE UNIQUE INDEX ON "private_chat_participants" ("chat_room_id", "user_id");

CREATE INDEX ON "private_chat_messages" ("chat_room_id", "sent_at");

CREATE INDEX ON "comments" ("course_id", "created_at");

CREATE INDEX ON "comments" ("step_id", "created_at");

CREATE INDEX ON "questions" ("test_id", "order_index");

CREATE INDEX ON "choice_questions" ("question_id");

CREATE UNIQUE INDEX ON "test_attempts" ("test_id", "user_id", "attempt_number");

CREATE INDEX ON "test_attempts" ("user_id", "started_at");

CREATE UNIQUE INDEX ON "user_answers" ("test_attempt_id", "question_id");

ALTER TABLE "user_contacts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_friends" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_friends" ADD FOREIGN KEY ("friend_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_bans" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_bans" ADD FOREIGN KEY ("banned_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "friend_requests" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "friend_requests" ADD FOREIGN KEY ("requester_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "courses" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "course_enrollments" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "course_enrollments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "course_memberships" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "course_memberships" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "course_memberships" ADD FOREIGN KEY ("granted_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "steps" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "step_edges" ADD FOREIGN KEY ("from_step_id") REFERENCES "steps" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "step_edges" ADD FOREIGN KEY ("to_step_id") REFERENCES "steps" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "step_edges" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "private_chat_rooms" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "private_chat_rooms" ADD FOREIGN KEY ("step_id") REFERENCES "steps" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "private_chat_participants" ADD FOREIGN KEY ("chat_room_id") REFERENCES "private_chat_rooms" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "private_chat_participants" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "private_chat_participants" ADD FOREIGN KEY ("last_read_message_id") REFERENCES "private_chat_messages" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "private_chat_messages" ADD FOREIGN KEY ("chat_room_id") REFERENCES "private_chat_rooms" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "private_chat_messages" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "private_chat_messages" ADD FOREIGN KEY ("reply_to_message_id") REFERENCES "private_chat_messages" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("author_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("step_id") REFERENCES "steps" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("parent_comment_id") REFERENCES "comments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "boards" ADD FOREIGN KEY ("step_id") REFERENCES "steps" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tests" ADD FOREIGN KEY ("step_id") REFERENCES "steps" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "questions" ADD FOREIGN KEY ("test_id") REFERENCES "tests" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "choice_questions" ADD FOREIGN KEY ("question_id") REFERENCES "questions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "test_attempts" ADD FOREIGN KEY ("test_id") REFERENCES "tests" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "test_attempts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_answers" ADD FOREIGN KEY ("test_attempt_id") REFERENCES "test_attempts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_answers" ADD FOREIGN KEY ("question_id") REFERENCES "questions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "choice_user_answers" ADD FOREIGN KEY ("user_answer_id") REFERENCES "user_answers" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "choice_user_answers" ADD FOREIGN KEY ("choice_question_id") REFERENCES "choice_questions" ("id") DEFERRABLE INITIALLY IMMEDIATE;
